Variable

In [ ]:

# Assigning values to variables
x <- 10 # Numeric variable
y = "Hello" # Character variable
z <- TRUE # Logical variable
# Printing variables
print(x) # Output: 10
print(y) # Output: "Hello"
print(z) # Output: TRU

[1] 10
[1] "Hello"
[1] TRUE


In [ ]:
var1 <- 5 # Valid
var.name <- 10 # Valid (using dot)
print(var.name)
# _var <- 20 # Invalid (starts with underscore)
# 2var <- 30 # Invalid (starts with a number)
# Case sensitivity
Var <- 100
var <- 200
print(Var) # Output: 100
print(var)
var.vicky<-500
print(var.vicky)
print(var)

[1] 10
[1] 100
[1] 200
[1] 500
[1] 200


In [ ]:
# Using <-
a <- 15
# Using =
b = 20
#Using ->
# 10->a
# Using assign() function
assign("c", 25)
# Printing all
print(a) # 15
print(b) # 20
print(c) # 25


[1] 15
[1] 20
[1] 25


In [ ]:
x <- 10 # x is numeric
x <- "R Programming" # Now x is character
print(x) # Output: "R Programming"

[1] "R Programming"


Comments

In [ ]:
# This is a single-line comment
# Multi-line comments can be written as:
# Line 1
# Line 2
# Line 3
# Alternatively, use if(FALSE) to block comment
x=10
if(FALSE){
 # This is a multi-line comment.
 # It won't be executed.
 x <- 5 + 10
}
print(x)
# Example with code
x <- 10 # Assigning 10 to x
y <- x * 2 # Doubling x and storing in y
print(y) # Output: 20


[1] 10
[1] 20


Keywords in R

In [ ]:
x <- 10
if (x > 5) {
 print("x is greater than 5")
} else {
 print("x is less than or equal to 5")
}
# Output: "x is greater than 5"
# Using for loop
for (i in 1:5) {
 print(i)
}
# Output: 1 2 3 4 5
# Using while loop
count <- 1
while (count <= 3) {
print(paste("Count is", count))
 count <- count + 1
}
# Output: "Count is 1", "Count is 2", "Count is 3"
# Using function
square <- function(x) {
 return(x * x)
}
print(square(4)) # Output: 16
# Using break in loop
for (i in 1:10) {
 if (i == 6) {
 break
 }
 print(i)
}
# Output: 1 2 3 4 5
# Using next (skip iteration)
for (i in 1:5) {
 if (i == 3) {
 next
 }
 print(i)
}


[1] "x is greater than 5"
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] "Count is 1"
[1] "Count is 2"
[1] "Count is 3"
[1] 16
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 1
[1] 2
[1] 4
[1] 5


Artihmetic operator

In [ ]:
a <- 10
b <- 3
print(a + b) # 13
print(a - b) # 7
print(a * b) # 30
print(a / b) # 3.333//floating point division
print(a ^ b) # 1000
print(a %% b) # 1 (remainder of integer division)
print(a %/% b) # 3 (quotient of integer division)


[1] 13
[1] 7
[1] 30
[1] 3.333333
[1] 1000
[1] 1
[1] 3


Relational Operators

In [ ]:
x=10
y=5
print(x==y)

print(x!=y)
print(x>y)
print(x<y)
print(x>=y)
print(x<=y)

[1] FALSE
[1] TRUE
[1] TRUE
[1] FALSE
[1] TRUE
[1] FALSE


Logical Operator

In [ ]:
a=TRUE
b=FALSE
print(a&b)
print(a | b)
print(!a)
print(a&&b)
print(a || b)

[1] FALSE
[1] TRUE
[1] FALSE
[1] FALSE
[1] TRUE


Assignment Operator

In [ ]:
x<-10
20->y
z=30
print(x)
print(y)
print(z)

[1] 10
[1] 20
[1] 30


Miscellaneous Operator

In [ ]:
seq<-1:5
print(seq)

print(3 %in% c(1,2,3))
mat1 <-matrix(1:4,nrow=2)
print(mat1)
mat2<-matrix(5:8,nrow=2)
print(mat1 %*% mat2)

[1] 1 2 3 4 5
[1] TRUE
     [,1] [,2]
[1,]    1    3
[2,]    2    4
     [,1] [,2]
[1,]   23   31
[2,]   34   46


R Data Types

In [ ]:
num = 10.5
int = 5L
char = "Hello"
bool = TRUE
comp = 3+2i
print(class(num))
print(class(int))
print(class(char))
print(class(bool))
print(class(comp))

[1] "numeric"
[1] "integer"
[1] "character"
[1] "logical"
[1] "complex"


In [ ]:
x=NULL
y=NA
z=Inf
w=NaN
print(x)
print(y)
print(z)
print(w)

NULL
[1] NA
[1] Inf
[1] NaN


In [ ]:
vec=c(1,2,3)
print(vec)

lst=list(1,"a",TRUE)
print(lst)

mat=matrix(1:4,nrow=1,ncol=4)
print(mat)

df = data.frame(
  name = c("Alice", "Bob"),
  age = c(25, 30),
  sex = c("Female", "Male")
)
print(df)

fac=factor(c("A","B","A"))
print(fac)

[1] 1 2 3
[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
   name age    sex
1 Alice  25 Female
2   Bob  30   Male
[1] A B A
Levels: A B


factors

In [ ]:
grades <- factor(c("A", "B", "A", "C","B","A","B","C"), levels = c("A", "B", "C", "D"))
print(grades)

[1] A B A C B A B C
Levels: A B C D


In [ ]:
responses <- c("iPhone", "Samsung", "iPhone", "Xiaomi", "Samsung")

all_brands <- c("iPhone", "Samsung", "Google", "Xiaomi", "OnePlus")

phone_factor <- factor(responses, levels = all_brands)

print(phone_factor)

table(phone_factor)

[1] iPhone  Samsung iPhone  Xiaomi  Samsung
Levels: iPhone Samsung Google Xiaomi OnePlus


phone_factor
 iPhone Samsung  Google  Xiaomi OnePlus 
      2       2       0       1       0 

In [ ]:
temperature <- factor(
 c("Low", "High", "Medium", "Low"),
 levels = c("Low", "Medium", "High"),
 ordered = TRUE
)
print(temperature)


colors <- factor(c("Red", "Blue", "Green"))
print(levels(colors)) # "Blue" "Green" "Red"
# Change levels
levels(colors) <- c("R", "B", "G")
print(colors) # R B



[1] Low    High   Medium Low   
Levels: Low < Medium < High
[1] "Blue"  "Green" "Red"  
[1] G R B
Levels: R B G


In [ ]:
f <- factor(c("Apple", "Banana", "Apple"))
print(as.character(f)) # "Apple" "Banana" "Apple"
print(as.numeric(f)) # 1 2 1 (internal codes)

[1] "Apple"  "Banana" "Apple" 
[1] 1 2 1


In [ ]:
f <- factor(c("A", "B", "A", "C"), levels = c("A", "B", "C", "D"))
f_new <- factor(f, levels = c("A", "B")) # Drops "C" and "D"
print(f_new) # A B A <NA>
# Remove unused levels
f_clean <- droplevels(f)
print(f_clean) # Levels: A B C

[1] A    B    A    <NA>
Levels: A B
[1] A B A C
Levels: A B C


In [ ]:
data <- data.frame(
 yield = c(10, 15, 12, 20),
 fertilizer = factor(c("A", "B", "A", "B"))
)
model <- lm(yield ~ fertilizer, data = data)
summary(model) # Compares A (baseline) vs. B



Call:
lm(formula = yield ~ fertilizer, data = data)

Residuals:
   1    2    3    4 
-1.0 -2.5  1.0  2.5 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)  
(Intercept)   11.000      1.904   5.777   0.0287 *
fertilizerB    6.500      2.693   2.414   0.1372  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.693 on 2 degrees of freedom
Multiple R-squared:  0.7445,	Adjusted R-squared:  0.6167 
F-statistic: 5.828 on 1 and 2 DF,  p-value: 0.1372



Call:
lm(formula = yield ~ fertilizer, data = data)

Residuals:
   1    2    3    4 
-1.0 -2.5  1.0  2.5 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)  
(Intercept)   11.000      1.904   5.777   0.0287 *
fertilizerB    6.500      2.693   2.414   0.1372  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.693 on 2 degrees of freedom
Multiple R-squared:  0.7445,	Adjusted R-squared:  0.6167 
F-statistic: 5.828 on 1 and 2 DF,  p-value: 0.1372


In [ ]:
data$fertilizer <- reorder(data$fertilizer, data$yield, FUN = mean)
print(levels(data$fertilizer)) # Sorted by mean yiel


[1] "A" "B"
